#!/bin/bash

## Description: Run all styles or selected one
## Usage: stl [option]
## Example: ddev stl\nddev stl -f version\nddev stl --fix <test-name>

if [ $# -eq 0 ] ; then
  vendor/bin/phpmd app,bootstrap,config,database,routes,tests text phpmd.xml &&
  vendor/bin/phpmnd --hint --progress --non-zero-exit-on-violation --extensions=all --allow-array-mapping --exclude=Orchid app &&
  vendor/bin/phpmnd --hint --progress --non-zero-exit-on-violation --allow-array-mapping database &&
  vendor/bin/phpmnd --hint --progress --non-zero-exit-on-violation --extensions=all --allow-array-mapping routes &&
  vendor/bin/phpmnd --hint --progress --non-zero-exit-on-violation --extensions=all --allow-array-mapping tests &&
  composer sniff
  exit
fi

if [ $@ == -f ] || [ $@ == --fix ] ; then
  composer lint
  exit
fi


