#!/bin/bash

## Description: Run phpunit tests
## Usage: test [option]
## Example: ddev test list\nddev test version\nddev test <test-name>

if [ $# -eq 0 ] ; then
  ./vendor/bin/phpunit
  exit
fi

case $1 in
  help)
    ./vendor/bin/phpunit --help
    exit
  ;;
  list|-l|--list)
    ./vendor/bin/phpunit --list-tests
    exit
  ;;
  version|-v|--version)
    ./vendor/bin/phpunit --version
    exit
  ;;
  -f|--filter)
    shift
    for var in "$@"
      do
        ./vendor/bin/phpunit --filter="$var"
    done
    exit
  ;;
  "$@")
    ./vendor/bin/phpunit "$@"
    exit
esac
